project_id = "groqsnnytvjabgeaekkw"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.retry-media-processing]
verify_jwt = false

[functions.whapi-webhook]
verify_jwt = false

[functions.whapi-send]
verify_jwt = false

[functions.whapi-configure]
verify_jwt = false

[functions.check-inactive-conversations]
verify_jwt = false

[functions.process-lead-evaluation]
verify_jwt = false

[functions.intelligent-transfer-orchestrator]
verify_jwt = false