project_id = "groqsnnytvjabgeaekkw"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.retry-media-processing]
verify_jwt = false

[functions.whapi-webhook]
verify_jwt = false

[functions.whapi-send]
verify_jwt = true

[functions.whapi-configure]
verify_jwt = true

[functions.check-inactive-conversations]
verify_jwt = false

[functions.process-lead-evaluation]
verify_jwt = false

[functions.intelligent-transfer-orchestrator]
verify_jwt = true

[functions.validate-whapi-token]
verify_jwt = true

[functions.diagnose-whapi-system]
verify_jwt = true

[functions.send-lead-to-seller]
verify_jwt = true

[functions.send-alert-to-managers]
verify_jwt = true

[functions.test-seller-delivery]
verify_jwt = true

[functions.get-secret]
verify_jwt = true

[functions.process-message-queue]
verify_jwt = false

[functions.dify-process-messages]
verify_jwt = false

[functions.check-pending-bot-messages]
verify_jwt = false

[functions.manual-process-queue]
verify_jwt = true

[functions.queue-scheduler]
verify_jwt = false

[functions.simple-test]
verify_jwt = false